/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mskalnik.gui;

import com.mskalnik.bl.AppointmentsHandler;
import com.mskalnik.bl.PatientsHandler;
import com.mskalnik.model.Appointment;
import com.mskalnik.model.Bill;
import com.mskalnik.model.Patient;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author mskalnik
 */
public class Bills extends javax.swing.JPanel {

    private static final PatientsHandler PATIENTS_HANDLER = new PatientsHandler();
    private static final AppointmentsHandler APPOINTMENTS_HANDLER = new AppointmentsHandler();
    /**
     * Creates new form Bill
     */
    public Bills() {
        initComponents();
        
        fillData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbPatient = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        liBill = new javax.swing.JList<>();
        btnCredit = new javax.swing.JButton();
        btnCash = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Make a Bill");
        add(jLabel1);
        jLabel1.setBounds(6, 6, 76, 19);

        jLabel2.setText("Patient:");
        add(jLabel2);
        jLabel2.setBounds(10, 30, 60, 30);

        cbPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPatientActionPerformed(evt);
            }
        });
        add(cbPatient);
        cbPatient.setBounds(90, 30, 250, 26);

        jLabel3.setText("Expenses:");
        add(jLabel3);
        jLabel3.setBounds(10, 70, 70, 16);

        jScrollPane1.setViewportView(liBill);

        add(jScrollPane1);
        jScrollPane1.setBounds(90, 70, 250, 131);

        btnCredit.setText("Credit");
        btnCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditActionPerformed(evt);
            }
        });
        add(btnCredit);
        btnCredit.setBounds(160, 210, 77, 32);

        btnCash.setText("Cash");
        btnCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashActionPerformed(evt);
            }
        });
        add(btnCash);
        btnCash.setBounds(90, 210, 59, 32);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreditActionPerformed

    private void btnCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCashActionPerformed

    private void cbPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPatientActionPerformed
        // TODO add your handling code here:
        String[] list = cbPatient.getSelectedItem().toString().split(":");
        int id = Integer.parseInt(list[0]);
                
        List<Bill> bills = APPOINTMENTS_HANDLER.getBill(id);
        DefaultListModel model = new DefaultListModel();
                
        if (bills != null) {
            for (Bill bill : bills) {
                if (!bill.getPayed()) {
                    model.addElement(bill.getIdBill() + ": " + bill.getMedication().getName() + " " + bill.getMedication().getPrice() + " HRK");
                }
            }
        } 
        liBill.setModel(model);
    }//GEN-LAST:event_cbPatientActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCash;
    private javax.swing.JButton btnCredit;
    private javax.swing.JComboBox<String> cbPatient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> liBill;
    // End of variables declaration//GEN-END:variables

    private void fillData() {
        cbPatient.removeAllItems();
        
        List<Patient> patients = PATIENTS_HANDLER.getExistingPatients();
        patients.forEach((patient) -> {
            cbPatient.addItem(patient.getOpid() + ": " + patient.getFirstName() + " " + patient.getSurname());
        });
    }
}
