/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mskalnik.gui;

/**
 *
 * @author mskalnik
 */
public class ComprehensiveFormPanel extends javax.swing.JPanel {

    /**
     * Creates new form ComprehensiveFormPanel
     */
    public ComprehensiveFormPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        basicPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtMiddleName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        contactPanel = new javax.swing.JPanel();
        kinPanel = new javax.swing.JPanel();
        personalPanel = new javax.swing.JPanel();
        professionPanel = new javax.swing.JPanel();
        lifestylePanel = new javax.swing.JPanel();
        basicComplaintsPanel = new javax.swing.JPanel();
        medicalComplaintsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        basicPanel.setLayout(null);

        jLabel2.setText("First name:");
        basicPanel.add(jLabel2);
        jLabel2.setBounds(10, 10, 76, 17);
        basicPanel.add(txtFirstName);
        txtFirstName.setBounds(120, 10, 560, 27);
        basicPanel.add(txtMiddleName);
        txtMiddleName.setBounds(120, 40, 560, 27);
        basicPanel.add(txtLastName);
        txtLastName.setBounds(120, 70, 560, 27);

        jLabel3.setText("Middle name:");
        basicPanel.add(jLabel3);
        jLabel3.setBounds(10, 40, 93, 17);

        jLabel4.setText("Last name:");
        basicPanel.add(jLabel4);
        jLabel4.setBounds(10, 70, 80, 17);

        jTabbedPane1.addTab("Basic", basicPanel);

        contactPanel.setLayout(null);
        jTabbedPane1.addTab("Contact", contactPanel);

        kinPanel.setLayout(null);
        jTabbedPane1.addTab("Nex-of-Kin", kinPanel);

        personalPanel.setLayout(null);
        jTabbedPane1.addTab("Personal", personalPanel);

        professionPanel.setLayout(null);
        jTabbedPane1.addTab("Profession", professionPanel);

        lifestylePanel.setLayout(null);
        jTabbedPane1.addTab("Lifestyle", lifestylePanel);

        basicComplaintsPanel.setLayout(null);
        jTabbedPane1.addTab("Basic Complaints", basicComplaintsPanel);

        medicalComplaintsPanel.setLayout(null);
        jTabbedPane1.addTab("Medical Complaints", medicalComplaintsPanel);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("Comprehensive registration form");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(292, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basicComplaintsPanel;
    private javax.swing.JPanel basicPanel;
    private javax.swing.JPanel contactPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel kinPanel;
    private javax.swing.JPanel lifestylePanel;
    private javax.swing.JPanel medicalComplaintsPanel;
    private javax.swing.JPanel personalPanel;
    private javax.swing.JPanel professionPanel;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMiddleName;
    // End of variables declaration//GEN-END:variables
}
