/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mskalnik.gui;

import java.awt.CardLayout;
import java.awt.Container;
import javax.swing.JPanel;

/**
 *
 * @author mskalnik
 */
public class Main extends javax.swing.JFrame {
    
    private JPanel current = null;

    /**
     * Creates new form MainForm
     */
    public Main() {
        initComponents();
        current = panelMiniForm1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMiniForm1 = new com.mskalnik.gui.PanelMiniForm();
        comprehensiveFormPanel1 = new com.mskalnik.gui.ComprehensiveFormPanel();
        mainMenuBar = new javax.swing.JMenuBar();
        menuReception = new javax.swing.JMenu();
        menuRegistration = new javax.swing.JMenu();
        miMiniForm = new javax.swing.JMenuItem();
        miComprehensive = new javax.swing.JMenuItem();
        miAppointements = new javax.swing.JMenuItem();
        miBill = new javax.swing.JMenuItem();
        menuPhysician = new javax.swing.JMenu();
        menuDoctor = new javax.swing.JMenu();
        menuManagement = new javax.swing.JMenu();
        miDaily = new javax.swing.JMenuItem();
        miWeekly = new javax.swing.JMenuItem();
        miMonthly = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Out Patient Management");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(panelMiniForm1, "card2");
        getContentPane().add(comprehensiveFormPanel1, "card3");

        menuReception.setText("Reception");

        menuRegistration.setText("Registration");

        miMiniForm.setText("Mini form");
        miMiniForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMiniFormActionPerformed(evt);
            }
        });
        menuRegistration.add(miMiniForm);

        miComprehensive.setText("Comprehensive form");
        miComprehensive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miComprehensiveActionPerformed(evt);
            }
        });
        menuRegistration.add(miComprehensive);

        menuReception.add(menuRegistration);

        miAppointements.setText("Appointements");
        menuReception.add(miAppointements);

        miBill.setText("Bill");
        menuReception.add(miBill);

        mainMenuBar.add(menuReception);

        menuPhysician.setText("Physician");
        mainMenuBar.add(menuPhysician);

        menuDoctor.setText("Doctor");
        mainMenuBar.add(menuDoctor);

        menuManagement.setText("Management");

        miDaily.setText("Daily report");
        menuManagement.add(miDaily);

        miWeekly.setText("Weekly report");
        menuManagement.add(miWeekly);

        miMonthly.setText("Monthly report");
        menuManagement.add(miMonthly);

        mainMenuBar.add(menuManagement);

        setJMenuBar(mainMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miMiniFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMiniFormActionPerformed
        // TODO add your handling code here:
        current.setVisible(false);
        panelMiniForm1.setVisible(true);
        current = panelMiniForm1;  
    }//GEN-LAST:event_miMiniFormActionPerformed

    private void miComprehensiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miComprehensiveActionPerformed
        // TODO add your handling code here:
        current.setVisible(false);
        comprehensiveFormPanel1.setVisible(true);
        current = comprehensiveFormPanel1;        
    }//GEN-LAST:event_miComprehensiveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);                
            }
        });
    }      

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mskalnik.gui.ComprehensiveFormPanel comprehensiveFormPanel1;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JMenu menuDoctor;
    private javax.swing.JMenu menuManagement;
    private javax.swing.JMenu menuPhysician;
    private javax.swing.JMenu menuReception;
    private javax.swing.JMenu menuRegistration;
    private javax.swing.JMenuItem miAppointements;
    private javax.swing.JMenuItem miBill;
    private javax.swing.JMenuItem miComprehensive;
    private javax.swing.JMenuItem miDaily;
    private javax.swing.JMenuItem miMiniForm;
    private javax.swing.JMenuItem miMonthly;
    private javax.swing.JMenuItem miWeekly;
    private com.mskalnik.gui.PanelMiniForm panelMiniForm1;
    // End of variables declaration//GEN-END:variables
}
