/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mskalnik.gui;

/**
 *
 * @author mskalnik
 */
public class Main extends javax.swing.JPanel {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabbedPanel = new javax.swing.JTabbedPane();
        receptionPanel = new javax.swing.JPanel();
        lblRegistration = new javax.swing.JLabel();
        lblAppointements = new javax.swing.JLabel();
        lblBill = new javax.swing.JLabel();
        btnMiniForm = new javax.swing.JButton();
        btnAppointment = new javax.swing.JButton();
        btnBill = new javax.swing.JButton();
        btnComprehensiveForm = new javax.swing.JButton();
        physicianPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        doctorPanel = new javax.swing.JPanel();
        managementPanel = new javax.swing.JPanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        receptionPanel.setLayout(new java.awt.GridLayout(3, 3));

        lblRegistration.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblRegistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistration.setText("Registration form:");
        lblRegistration.setToolTipText("");
        receptionPanel.add(lblRegistration);

        lblAppointements.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblAppointements.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAppointements.setText("Appointements:");
        receptionPanel.add(lblAppointements);

        lblBill.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblBill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBill.setText("Bill:");
        receptionPanel.add(lblBill);

        btnMiniForm.setText("Mini form");
        receptionPanel.add(btnMiniForm);

        btnAppointment.setText("Make appointment");
        receptionPanel.add(btnAppointment);

        btnBill.setText("New bill");
        receptionPanel.add(btnBill);

        btnComprehensiveForm.setText("Comprehensive form");
        receptionPanel.add(btnComprehensiveForm);

        mainTabbedPanel.addTab("Reception", receptionPanel);

        physicianPanel.setLayout(new javax.swing.BoxLayout(physicianPanel, javax.swing.BoxLayout.LINE_AXIS));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        physicianPanel.add(jScrollPane1);

        mainTabbedPanel.addTab("Physician", physicianPanel);

        javax.swing.GroupLayout doctorPanelLayout = new javax.swing.GroupLayout(doctorPanel);
        doctorPanel.setLayout(doctorPanelLayout);
        doctorPanelLayout.setHorizontalGroup(
            doctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );
        doctorPanelLayout.setVerticalGroup(
            doctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );

        mainTabbedPanel.addTab("Doctor", doctorPanel);

        javax.swing.GroupLayout managementPanelLayout = new javax.swing.GroupLayout(managementPanel);
        managementPanel.setLayout(managementPanelLayout);
        managementPanelLayout.setHorizontalGroup(
            managementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );
        managementPanelLayout.setVerticalGroup(
            managementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );

        mainTabbedPanel.addTab("Management", managementPanel);

        add(mainTabbedPanel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppointment;
    private javax.swing.JButton btnBill;
    private javax.swing.JButton btnComprehensiveForm;
    private javax.swing.JButton btnMiniForm;
    private javax.swing.JPanel doctorPanel;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAppointements;
    private javax.swing.JLabel lblBill;
    private javax.swing.JLabel lblRegistration;
    private javax.swing.JTabbedPane mainTabbedPanel;
    private javax.swing.JPanel managementPanel;
    private javax.swing.JPanel physicianPanel;
    private javax.swing.JPanel receptionPanel;
    // End of variables declaration//GEN-END:variables
}
