/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mskalnik.gui;

/**
 *
 * @author mskalnik
 */
public class PanelMiniForm extends javax.swing.JPanel {

    /**
     * Creates new form panelMiniForm
     */
    public PanelMiniForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMiniForm = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();

        panelMiniForm.setLayout(null);
        panelMiniForm.add(jLabel12);
        jLabel12.setBounds(346, 5, 341, 29);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("Mini registration form");
        panelMiniForm.add(jLabel1);
        jLabel1.setBounds(10, 10, 341, 29);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setText("Patient");
        panelMiniForm.add(jLabel2);
        jLabel2.setBounds(10, 40, 70, 29);
        panelMiniForm.add(jLabel13);
        jLabel13.setBounds(346, 44, 341, 29);

        jLabel3.setText("First name:");
        panelMiniForm.add(jLabel3);
        jLabel3.setBounds(10, 70, 80, 29);

        jTextField1.setColumns(1);
        panelMiniForm.add(jTextField1);
        jTextField1.setBounds(130, 70, 550, 29);

        jLabel4.setText("Middle name:");
        panelMiniForm.add(jLabel4);
        jLabel4.setBounds(10, 100, 100, 29);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        panelMiniForm.add(jTextField2);
        jTextField2.setBounds(130, 100, 550, 29);

        jLabel5.setText("Last name:");
        panelMiniForm.add(jLabel5);
        jLabel5.setBounds(10, 130, 80, 29);
        panelMiniForm.add(jTextField3);
        jTextField3.setBounds(130, 130, 550, 29);

        jLabel6.setText("Date of birth:");
        panelMiniForm.add(jLabel6);
        jLabel6.setBounds(10, 160, 100, 29);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        panelMiniForm.add(jComboBox1);
        jComboBox1.setBounds(490, 160, 190, 29);

        jLabel7.setText("Complaint:");
        panelMiniForm.add(jLabel7);
        jLabel7.setBounds(10, 190, 80, 29);

        jTextArea1.setColumns(40);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        panelMiniForm.add(jScrollPane1);
        jScrollPane1.setBounds(130, 190, 550, 120);

        jLabel8.setText("Telephone 1:");
        panelMiniForm.add(jLabel8);
        jLabel8.setBounds(10, 320, 90, 29);
        panelMiniForm.add(jTextField4);
        jTextField4.setBounds(130, 320, 550, 29);

        jLabel9.setText("Telephone  2:");
        panelMiniForm.add(jLabel9);
        jLabel9.setBounds(10, 350, 100, 29);
        panelMiniForm.add(jTextField5);
        jTextField5.setBounds(130, 350, 550, 29);

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel10.setText("Next of Kin");
        panelMiniForm.add(jLabel10);
        jLabel10.setBounds(10, 390, 110, 29);
        panelMiniForm.add(jLabel14);
        jLabel14.setBounds(346, 356, 341, 29);

        jLabel11.setText("First name:");
        panelMiniForm.add(jLabel11);
        jLabel11.setBounds(10, 420, 90, 29);
        panelMiniForm.add(jTextField6);
        jTextField6.setBounds(130, 420, 550, 29);

        jLabel15.setText("Middle name:");
        panelMiniForm.add(jLabel15);
        jLabel15.setBounds(10, 450, 100, 29);
        panelMiniForm.add(jTextField7);
        jTextField7.setBounds(130, 450, 550, 29);

        jLabel16.setText("Last name:");
        panelMiniForm.add(jLabel16);
        jLabel16.setBounds(10, 480, 80, 29);
        panelMiniForm.add(jTextField8);
        jTextField8.setBounds(130, 480, 550, 29);

        jLabel17.setText("Relationship:");
        panelMiniForm.add(jLabel17);
        jLabel17.setBounds(10, 510, 90, 29);
        panelMiniForm.add(jTextField9);
        jTextField9.setBounds(130, 510, 550, 29);

        jButton1.setText("Confirm");
        panelMiniForm.add(jButton1);
        jButton1.setBounds(130, 540, 550, 29);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelMiniForm.add(jComboBox2);
        jComboBox2.setBounds(310, 160, 180, 27);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelMiniForm.add(jComboBox3);
        jComboBox3.setBounds(130, 160, 180, 27);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMiniForm, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMiniForm, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel panelMiniForm;
    // End of variables declaration//GEN-END:variables
}
