/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mskalnik.gui;

import com.mskalnik.model.Doctor;
import com.mskalnik.bl.DoctorsHandler;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author mskalnik
 */
public class PhysicianList extends javax.swing.JPanel {

    private static final DoctorsHandler DOCTORS_HANDLER = new DoctorsHandler();
    /**
     * Creates new form DoctorPanel
     */
    public PhysicianList() {
        initComponents();
        
        fillList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        liDoctors = new javax.swing.JList<>();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Doctor List");
        add(jLabel1);
        jLabel1.setBounds(6, 6, 110, 19);

        jScrollPane1.setViewportView(liDoctors);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 30, 380, 260);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate);
        btnUpdate.setBounds(10, 300, 80, 32);

        btnDelete.setText("Delete");
        add(btnDelete);
        btnDelete.setBounds(100, 300, 66, 32);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        fillList();
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> liDoctors;
    // End of variables declaration//GEN-END:variables

    private void fillList() {
        List<Doctor> doctors = DOCTORS_HANDLER.getDoctors();
        DefaultListModel model = new DefaultListModel();
        
        for (Doctor doctor : doctors) {
            model.addElement(doctor.getIdDoctor() + ": " + doctor.getTitle() + " " + doctor.getFirstName() + " " + doctor.getSurname());
        }
        
        liDoctors.setModel(model);
    }
}
