/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mskalnik.gui;

/**
 *
 * @author mskalnik
 */
public class PhysicianAdd extends javax.swing.JPanel {

    /**
     * Creates new form AddDoctor
     */
    public PhysicianAdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Add a Doctor");
        add(jLabel1);
        jLabel1.setBounds(6, 6, 90, 19);

        jLabel2.setText("First Name:");
        add(jLabel2);
        jLabel2.setBounds(10, 40, 64, 20);

        jLabel3.setText("Middle Name:");
        add(jLabel3);
        jLabel3.setBounds(10, 70, 76, 16);

        jLabel4.setText("Last Name:");
        add(jLabel4);
        jLabel4.setBounds(10, 100, 64, 16);

        jLabel5.setText("Title:");
        add(jLabel5);
        jLabel5.setBounds(10, 130, 27, 16);
        add(jTextField1);
        jTextField1.setBounds(100, 130, 250, 24);
        add(jTextField2);
        jTextField2.setBounds(100, 40, 250, 24);
        add(jTextField3);
        jTextField3.setBounds(100, 70, 250, 24);
        add(jTextField4);
        jTextField4.setBounds(100, 100, 250, 24);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
