/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mskalnik.gui;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author mskalnik
 */
public class Welcome extends javax.swing.JPanel {

    
    private static final String IMG_PATH = "logo.jpg";
        
    /**
     * Creates new form Welcome
     */
    public Welcome() {
        initComponents();
        
        /*try {
        BufferedImage img = ImageIO.read(new File(IMG_PATH));
        ImageIcon icon = new ImageIcon(img);
        JLabel label = new JLabel(icon);
        JOptionPane.showMessageDialog(null, label);
        } catch (IOException e) {
        e.printStackTrace();
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Welcome to Out Patient Management Module!");
        add(jLabel1);
        jLabel1.setBounds(14, 6, 527, 120);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
